// Code generated by mockery v2.38.0. DO NOT EDIT.

package ports

import (
	context "context"

	domain "github.com/huytran2000-hcmus/grpc-microservices/order/internal/appication/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockPaymentPort is an autogenerated mock type for the PaymentPort type
type MockPaymentPort struct {
	mock.Mock
}

type MockPaymentPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentPort) EXPECT() *MockPaymentPort_Expecter {
	return &MockPaymentPort_Expecter{mock: &_m.Mock}
}

// Charge provides a mock function with given fields: _a0, _a1
func (_m *MockPaymentPort) Charge(_a0 context.Context, _a1 *domain.Order) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Charge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Order) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentPort_Charge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Charge'
type MockPaymentPort_Charge_Call struct {
	*mock.Call
}

// Charge is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *domain.Order
func (_e *MockPaymentPort_Expecter) Charge(_a0 interface{}, _a1 interface{}) *MockPaymentPort_Charge_Call {
	return &MockPaymentPort_Charge_Call{Call: _e.mock.On("Charge", _a0, _a1)}
}

func (_c *MockPaymentPort_Charge_Call) Run(run func(_a0 context.Context, _a1 *domain.Order)) *MockPaymentPort_Charge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Order))
	})
	return _c
}

func (_c *MockPaymentPort_Charge_Call) Return(_a0 error) *MockPaymentPort_Charge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentPort_Charge_Call) RunAndReturn(run func(context.Context, *domain.Order) error) *MockPaymentPort_Charge_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentPort creates a new instance of MockPaymentPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentPort {
	mock := &MockPaymentPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
