apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "grpc-microservices.labels" . | nindent 4}}
data:
  initdb.sql: |
    CREATE DATABASE order_service;
    CREATE DATABASE payment_service;

    CREATE USER 'payment_service'@'%' IDENTIFIED BY 'verysecretpass';
    CREATE USER 'order_service'@'%' IDENTIFIED BY 'verysecretpass';

    GRANT ALL PRIVILEGES ON order_service.* TO 'order_service'@'%';
    GRANT ALL PRIVILEGES ON payment_service.* TO 'payment_service'@'%';
immutable: true
