apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: {{ .Release.Namespace}}
  labels: 
    name: order
    {{- include "grpc-microservices.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount.order }}
  selector:
    matchLabels:
      service: order
  template:
    metadata:
      labels: 
        service: order
        {{- include "grpc-microservices.labels" . | nindent 8}}
    spec:
      initContainers:
        {{- include "initContainer.mysqlWait" . | nindent 6 }}
      containers:
      - name: order
        image: "huypk2000/grpc-order-service:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ENV
          value: "prod"
        - name: APPLICATION_PORT
          value: {{ .Values.service.orderPort | quote }}
        - name: DATA_SOURCE_URL
          value: "order_service:verysecretpass@tcp({{ .Release.Name }}-mysql:3306)/order_service?charset=utf8mb4&parseTime=True&loc=Local"
        - name: PAYMENT_SERVICE_URL
          value: "payment:{{ .Values.service.paymentPort }}"
        - name: OTLP_ENDPOINT
          value: "jaeger-open-search-telemetry-collector:4317"
        ports:
        - containerPort: {{ .Values.service.orderPort }}
        readinessProbe:
          grpc:
            port: {{ .Values.service.orderPort }}
          initialDelaySeconds: 1
          periodSeconds: 1
        livenessProbe:
          grpc:
            port: {{ .Values.service.orderPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
