apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: {{ .Release.Namespace}}
  labels:
    name: payment
    {{- include "grpc-microservices.labels" . | nindent 4}}
spec:
  selector:
    service: payment
  ports:
    - name: grpc
      port: {{ .Values.service.paymentPort }}
      protocol: TCP
      targetPort: {{ .Values.service.paymentPort }}
      appProtocol: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: {{ .Release.Namespace}}
  labels: 
    name: payment
    {{- include "grpc-microservices.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount.payment }}
  selector:
    matchLabels:
      service: payment
  template:
    metadata:
      labels: 
        service: payment
        {{- include "grpc-microservices.labels" . | nindent 8}}
    spec:
      initContainers:
      - name: mysql-wait
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup {{ .Release.Name }}-mysql; do echo waiting for mysql; sleep 2; done']
      containers:
      - name: payment
        image: "huypk2000/grpc-payment-service:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: ENV
            value: "prod"
          - name: APPLICATION_PORT
            value: {{ .Values.service.paymentPort | quote }}
          - name: DATA_SOURCE_URL
            value: "payment_service:verysecretpass@tcp({{ .Release.Name }}-mysql:3306)/payment_service?charset=utf8mb4&parseTime=True&loc=Local"
        ports:
          - containerPort: {{ .Values.service.paymentPort }}
        readinessProbe:
          grpc:
            port: {{ .Values.service.paymentPort }}
          initialDelaySeconds: 1
        livenessProbe:
          grpc:
            port: {{ .Values.service.paymentPort }}
          initialDelaySeconds: 10
