replicaCount: 
  order: 1
  payment: 1

image:
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  orderPort: "8080"
  paymentPort: "8081"

mysql:
  auth:
    rootPassword: "verysecretpassword"
  initdbScriptsConfigMap: mysql-initdb-config

ingress:
  tls: true

cert-manager:
  enabled: true
  installCRDs: true

fluent-bit:
  config:
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
    outputs: |
      [OUTPUT]
          Name opensearch
          Match kube.*
          Host opensearch-cluster-master
          Logstash_Format On
          Logstash_Prefix kubernetes_nodes_logs
          Suppress_Type_Name On
          Retry_Limit 5
          HTTP_User admin
          HTTP_Passwd admin
          tls On
          tls.verify Off

opensearch:
  replicas: 1
